"""add raiting

Revision ID: d57d43e00198
Revises: e0725eb283e2
Create Date: 2022-08-25 19:27:10.716900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d43e00198'
down_revision = 'e0725eb283e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('raiting', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'raiting')
    # ### end Alembic commands ###
